name: Continuous Deployment

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment to deploy to
        default: Staging
        options: 
        - Staging
        - Production
 
permissions:
  contents: write
  packages: write
  repository-projects: write
  id-token: write

jobs:

  version:
    uses: codedesignplus/workflows/.github/workflows/release.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Users
      microservice-name: ms-users
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  container:
    needs: version
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' }}
    uses: codedesignplus/workflows/.github/workflows/container-image.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Users
      microservice-name: ms-users
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
  
  deploy:
    needs: container
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' }}
    uses: codedesignplus/workflows/.github/workflows/deploy.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Users
      microservice-name: ms-users
      enable-rest: true
      enable-grpc: false
      enable-worker: false
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit